### ISSUE TITLE
Try out robotjs

### ISSUE THREAD

**Issue by pomodorozhong** [pomodorozhong/personal-research#13]
## Todo
- [x] To try autokey
- [ ] To try automagica
- [ ] To try robotjs

## Reference
+ [octalmage/robotjs: Node.js Desktop Automation.](https://github.com/octalmage/robotjs)
+ [automagica/automagica: Open Source RPA 🤖 Robotic Process Automation](https://github.com/automagica/automagica)
+ [autokey/autokey: AutoKey, a desktop automation utility for Linux and X11.](https://github.com/autokey/autokey)

**Comment by pomodorozhong** [comment]
Before tying it out, I should know if there is any alternatives got more user base.

**Comment by pomodorozhong** [comment]
Alternatives
+ [robotjs vs Automagica | LibHunt](https://cpp.libhunt.com/compare-robotjs-vs-automagica)
+ [robotjs vs AutoKey | LibHunt](https://cpp.libhunt.com/compare-robotjs-vs-autokey)

**Comment by pomodorozhong** [comment]
It seems AutoHotKey is way more eazy to use on Windows, there's no need to consider alternatives for now.
